// This code was generated by GPT-5 as an example for how to instantiate and retrieve data from our database. 

import java.sql.*;

public class DatabaseExample {

    private static final String DB_URL = "jdbc:sqlite:app.db";

    public static void main(String[] args) {
        try {
            // Step 2: Connect to Database
            Connection conn = DriverManager.getConnection(DB_URL);  // Connects or creates the .db file if it doesn't exist

            // Step 3: Create Tables and Seed Data (e.g., on first run)
            Statement stmt = conn.createStatement();
            stmt.execute("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, name TEXT);");  // Creates table if not present
            // Optional: Seed initial data if needed (check for emptiness first in real app)
            stmt.executeUpdate("INSERT OR IGNORE INTO users (id, name) VALUES (1, 'Meydup Nem');");  // Example seed insert

            // Step 4: Store Data (e.g., insert a new user)
            PreparedStatement pstmt = conn.prepareStatement("INSERT INTO users (name) VALUES (?)");
            pstmt.setString(1, "New User");  // Parameterized to prevent SQL injection
            pstmt.executeUpdate();  // Persists the change to the .db file

            // Step 5: Retrieve Data (e.g., query and print existing users)
            ResultSet rs = stmt.executeQuery("SELECT * FROM users;");
            while (rs.next()) {
                System.out.println("User ID: " + rs.getInt("id") + ", Name: " + rs.getString("name"));
            }

            // Step 6: Close Resources and Handle Errors (using try-with-resources for auto-closing)
            // Note: In a full app, wrap the whole block in try-with-resources for conn and stmt
            rs.close();
            pstmt.close();
            stmt.close();
            conn.close();  // Ensures data is flushed to disk
            System.out.println("Resources closed successfully.");

        } catch (SQLException e) {
            // Step 6 (continued): Error handling
            System.err.println("Database error: " + e.getMessage());
            e.printStackTrace();
        }
    }
}